Verify inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -55,6 +55,14 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Verify input
+      shell: bash
+      run: |
+        if [ "${{inputs.flavor}}" == "ubuntu" ] && [ "${{inputs.platform}}" == "i386" ]; then
+          echo "::error::Platform i386 is not supported for Ubuntu"
+          exit 1
+        fi
+
     - name: Checkout
       uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
 
@@ -86,10 +94,10 @@ runs:
 
     - name: Build package
       shell: bash
-      run: docker run -v "/var/run/docker.sock":"/var/run/docker.sock" -v "${{inputs.source_dir}}":/source --env INPUT_FLAVOR --env INPUT_DIST --env INPUT_PLATFORM --env INPUT_SOURCEPACKAGE --env INPUT_SOURCE_DIR --env INPUT_RESULT_DIR --env INPUT_ENABLE_LLSO --env INPUT_ENABLE_PSO --env INPUT_DEB_FULLNAME --env INPUT_DEB_EMAIL --env INPUT_PRERELEASE_TAG --workdir /source --platform="linux/${{inputs.platform}}" "ghcr.io/${{github.actor}}/sil-${{inputs.flavor}}-${{inputs.dist}}-${{inputs.platform}}-${{inputs.enable_pso}}-${{inputs.enable_llso}}" "${{inputs.dist}}" "${{inputs.sourcepackage}}" .
+      run: docker run -v "/var/run/docker.sock":"/var/run/docker.sock" -v "${{inputs.source_dir}}":/source --env INPUT_DISTRIBUTION --env INPUT_DIST --env INPUT_PLATFORM --env INPUT_SOURCEPACKAGE --env INPUT_SOURCE_DIR --env INPUT_RESULT_DIR --env INPUT_ENABLE_LLSO --env INPUT_ENABLE_PSO --env INPUT_DEB_FULLNAME --env INPUT_DEB_EMAIL --env INPUT_PRERELEASE_TAG --workdir /source --platform="linux/${{inputs.platform}}" "ghcr.io/${{github.actor}}/sil-${{inputs.flavor}}-${{inputs.dist}}-${{inputs.platform}}-${{inputs.enable_pso}}-${{inputs.enable_llso}}" "${{inputs.dist}}" "${{inputs.sourcepackage}}" .
       working-directory: ${{inputs.source_dir}}
       env:
-        INPUT_FLAVOR: "${{inputs.flavor}}"
+        INPUT_DISTRIBUTION: "${{inputs.flavor}}"
         INPUT_DIST: "${{inputs.dist}}"
         INPUT_PLATFORM: "${{inputs.platform}}"
         INPUT_SOURCEPACKAGE: "${{inputs.sourcepackage}}"
